apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: redis-container
      image: redis
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret1
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret1
              key: password
  restartPolicy: Never
