apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-example
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-example
              image: busybox
              command:
                - /bin/sh
                - -c
                - echo "Hello Cron Job"
          restartPolicy: OnFailure
